name: Publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Extract version
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/refs\/tags\/v/, '');

      - name: Publish npm
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: yarn
      - run: yarn build
      - run: yarn publish --new-version ${{ steps.tag.outputs.result }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
